#!/usr/bin/env python
#
# Load a system.map file (generated by 'nm')
# so that you can play with symbols
#
import sys
import struct

from symbols        import SymTab, SymParser
from ramooflax      import VM, CPUFamily, log, disassemble
from ramooflax      import AddrSpace, PgMsk, Page, PageTable

#
# Main
#
if len(sys.argv) < 2:
    print "give me 'system.map"
    sys.exit(1)

# load kernel symbols
vm.symbols = SymTab(SymParser().from_system_map(sys.argv[1]))

peer = "172.16.131.128:1337"
vm = VM(CPUFamily.Intel, peer)

vm.ads = {}

log.setup(info=True, fail=True,
          gdb=False, vm=True,
          ads=False, brk=True, evt=False)

vm.attach()
vm.stop()

print vm.symbols[vm.cpu.code_location()]

log("info", "ready!")
vm.interact2(dict(globals(), **locals()))
